require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RegionSetMembershipsController do

  # This should return the minimal set of attributes required to create a valid
  # RegionSetMembership. As you add validations to RegionSetMembership, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "region_set_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RegionSetMembershipsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all region_set_memberships as @region_set_memberships" do
      region_set_membership = RegionSetMembership.create! valid_attributes
      get :index, {}, valid_session
      assigns(:region_set_memberships).should eq([region_set_membership])
    end
  end

  describe "GET show" do
    it "assigns the requested region_set_membership as @region_set_membership" do
      region_set_membership = RegionSetMembership.create! valid_attributes
      get :show, {:id => region_set_membership.to_param}, valid_session
      assigns(:region_set_membership).should eq(region_set_membership)
    end
  end

  describe "GET new" do
    it "assigns a new region_set_membership as @region_set_membership" do
      get :new, {}, valid_session
      assigns(:region_set_membership).should be_a_new(RegionSetMembership)
    end
  end

  describe "GET edit" do
    it "assigns the requested region_set_membership as @region_set_membership" do
      region_set_membership = RegionSetMembership.create! valid_attributes
      get :edit, {:id => region_set_membership.to_param}, valid_session
      assigns(:region_set_membership).should eq(region_set_membership)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RegionSetMembership" do
        expect {
          post :create, {:region_set_membership => valid_attributes}, valid_session
        }.to change(RegionSetMembership, :count).by(1)
      end

      it "assigns a newly created region_set_membership as @region_set_membership" do
        post :create, {:region_set_membership => valid_attributes}, valid_session
        assigns(:region_set_membership).should be_a(RegionSetMembership)
        assigns(:region_set_membership).should be_persisted
      end

      it "redirects to the created region_set_membership" do
        post :create, {:region_set_membership => valid_attributes}, valid_session
        response.should redirect_to(RegionSetMembership.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved region_set_membership as @region_set_membership" do
        # Trigger the behavior that occurs when invalid params are submitted
        RegionSetMembership.any_instance.stub(:save).and_return(false)
        post :create, {:region_set_membership => { "region_set_id" => "invalid value" }}, valid_session
        assigns(:region_set_membership).should be_a_new(RegionSetMembership)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RegionSetMembership.any_instance.stub(:save).and_return(false)
        post :create, {:region_set_membership => { "region_set_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested region_set_membership" do
        region_set_membership = RegionSetMembership.create! valid_attributes
        # Assuming there are no other region_set_memberships in the database, this
        # specifies that the RegionSetMembership created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RegionSetMembership.any_instance.should_receive(:update_attributes).with({ "region_set_id" => "1" })
        put :update, {:id => region_set_membership.to_param, :region_set_membership => { "region_set_id" => "1" }}, valid_session
      end

      it "assigns the requested region_set_membership as @region_set_membership" do
        region_set_membership = RegionSetMembership.create! valid_attributes
        put :update, {:id => region_set_membership.to_param, :region_set_membership => valid_attributes}, valid_session
        assigns(:region_set_membership).should eq(region_set_membership)
      end

      it "redirects to the region_set_membership" do
        region_set_membership = RegionSetMembership.create! valid_attributes
        put :update, {:id => region_set_membership.to_param, :region_set_membership => valid_attributes}, valid_session
        response.should redirect_to(region_set_membership)
      end
    end

    describe "with invalid params" do
      it "assigns the region_set_membership as @region_set_membership" do
        region_set_membership = RegionSetMembership.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RegionSetMembership.any_instance.stub(:save).and_return(false)
        put :update, {:id => region_set_membership.to_param, :region_set_membership => { "region_set_id" => "invalid value" }}, valid_session
        assigns(:region_set_membership).should eq(region_set_membership)
      end

      it "re-renders the 'edit' template" do
        region_set_membership = RegionSetMembership.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RegionSetMembership.any_instance.stub(:save).and_return(false)
        put :update, {:id => region_set_membership.to_param, :region_set_membership => { "region_set_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested region_set_membership" do
      region_set_membership = RegionSetMembership.create! valid_attributes
      expect {
        delete :destroy, {:id => region_set_membership.to_param}, valid_session
      }.to change(RegionSetMembership, :count).by(-1)
    end

    it "redirects to the region_set_memberships list" do
      region_set_membership = RegionSetMembership.create! valid_attributes
      delete :destroy, {:id => region_set_membership.to_param}, valid_session
      response.should redirect_to(region_set_memberships_url)
    end
  end

end
